#!/bin/bash

domain=$1
# Check if args passed
if [ -z "$1" ]
then
#  Ask for domain name
  echo "Domain name:"
    read domain

fi

echo "Location to files (default current directory):"
echo "Please note that the location must be readable by the nginx user."
echo "For best results use a directory in /var/www"
read location

# if location is empty, use current directory
if [ -z "$location" ]
then
  location=$PWD
fi

# Install nginx
sudo apt update
sudo apt-get install nginx certbot python3-certbot-nginx -y
# Setup NGINX config
printf "server {
  listen 80;
  listen [::]:80;
  root $location;
  index index.html;
  server_name $domain;

    location / {
        try_files \$uri \$uri/ @htmlext;
    }

    location ~ \.html$ {
        try_files \$uri =404;
    }

    location @htmlext {
        rewrite ^(.*)$ \$1.html last;
    }
    error_page 404 /404.html;
    location = /404.html {
            internal;
    }
    location = /.well-known/wallets/HNS {
        add_header Cache-Control 'must-revalidate';
        add_header Content-Type text/plain;
    }
}
" > /etc/nginx/sites-available/$domain
sudo ln -s /etc/nginx/sites-available/$domain /etc/nginx/sites-enabled/$domain

# LetsEncrypt SSL Certificate
sudo certbot --nginx -d $domain

# Add cert renewal to cron
crontab -l > cron
printf "0 12 * * * /usr/bin/certbot renew --quiet
" > cron
crontab cron
rm cron

# Restart to apply config file
sudo chmod a+rx $location
sudo systemctl restart nginx