#!/bin/bash

domain=$1
url=$2

# Check if args passed
if [ -z "$1" ]
then
#  Ask for domain name
  echo "Domain name:"
    read domain

fi

if [ -z "$2" ]
then
#  Ask for domain name
  echo "URL:"
    read url

fi

# Install nginx
sudo apt update
sudo apt-get install nginx certbot python3-certbot-nginx -y
# Setup NGINX config
printf "server {
  listen 80;
  listen [::]:80;
  server_name $domain;
  proxy_ssl_server_name on;
  location / {
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_pass $url;
    }
}" > /etc/nginx/sites-available/$domain
sudo ln -s /etc/nginx/sites-available/$domain /etc/nginx/sites-enabled/$domain

# LetsEncrypt SSL Certificate
sudo certbot --nginx -d $domain

# Add cert renewal to cron
crontab -l > cron
printf "0 12 * * * /usr/bin/certbot renew --quiet
" > cron
crontab cron
rm cron

# Restart to apply config file
sudo systemctl restart nginx
